### PR TITLE
Fix some details for pull request #136

### PR DESCRIPTION
**Pull request by eduramiba**
Thanks for the pull request https://github.com/gephi/gephi-plugins/pull/136 :) You will need to accept a few changes before merging.

### CODE REVIEW

**Comment by michihenninger** [comment]
Hi @eduramiba . Thanks for reviewing my merge-request. Now I see how to use that processTicket ;-). Also thanks for all the effort you put into gephi plugin maintaining!
One last question before finally merging and accepting: Do you know why the report istn't show as a popup after the calculation? In all other statistics it works that way.

Thanks a lot and have a nice day!
Michi

**Comment by eduramiba** [comment]
I don't know why the report is not showing. I spent some time trying to figure it out but I can't find the problem... :sob:

**Comment by michihenninger** [comment]
Hi @eduramiba . Thanks for the quick response. Don't worry, it's not that important. I'm quite happy to provide my first gephi plugin (and my first open source implementation). I am lecturer for Social Network Analysis and using gephi in my course. A great tool! Simple to use and powerful! Maybe more plugins are comming ;-)

**Comment by eduramiba** [comment]
Awesome! :) I will merge your plugin soon.
If the problem is fixed later, the plugin can be easily updated.

**Pull request merged**
